openapi: 3.0.1
info:
  title: Gestionnaire d'Classes
  description:
    Une application de gestion des classes permet aux utilisateurs de visualiser
    une liste complète d'classes, d'ajouter de nouveaux classes à la base de données
    et de supprimer des classes existants de manière intuitive.

  contact:
    name: API Support Safran engineering services
    email: fathi.yassinee@gmail.com
    url: https://www.bezkoder.com/spring-boot-swagger-3/
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: URL du serveur généré
tags:
  - name: classes
    description: Gestionnaire d'classes

