spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-dev-master.xml
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK # Name of table to use for tracking concurrent Liquibase usage.
    default-schema: testdb
    enabled: true
    drop-first: true
    user: sa
    password:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

  test:
    database:
      replace: none
  logging:
    level:
      org:
        hibernate:
          type: trace
  profiles:
    active: test