server:
  port: 8080

log4j:
  logger:
    org:
      hibernate:
        SQL: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classes-db?createDatabaseIfNotExist=true
    username: root
    password: root
  message:
    resource

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-dev-master.xml
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK # Name of table to use for tracking concurrent Liquibase usage.
    default-schema: classes-db
    enabled: true
    drop-first: false
    user: root
    password: root

springdoc:
  swagger-ui:
    path: /documentation/etudiant.html
    enabled: true
    urls:
      - url: /swagger.yaml
        name: student